title:              Deep Robotics
email:              kulunu@gmail.com
description:        Research on Deep learning methods for Robotic Manipulation
author:             Kulunu Osanda
baseurl:            ""
url:                ""

# Social Profiles
twitter_username:   KulunuOsanda
github_username:    KulunuOS
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
